{{- if gt (int .Values.kubeScheduler.controlPlaneReplicas) 2 }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-scheduler
  namespace: kube-system
  labels:
    tier: control-plane
    k8s-app: kube-scheduler
spec:
  selector:
    matchLabels:
      tier: control-plane
      k8s-app: kube-scheduler
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        tier: control-plane
        k8s-app: kube-scheduler
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: 'docker/default'
    spec:
{{- template "scheduler-containers" . }}
{{- end }}
